#!/bin/bash
clear
echo -e ""
echo -e "==========================-Qolko-=========================="
echo -e "* menu         : List of Main Commands"
echo -e ""
echo -e "=========================-SSH & SlowDNS-========================"
echo -e "* usernew      : Create SSH & SlowDNS Account"
echo -e "* trial        : Generate SSH & SlowDNS Trial Account"
echo -e "* renew        : Extending SSH & SlowDNS Account Active Life"
echo -e "* deluser      : Delete SSH & SlowDNS Account"
echo -e "* cek          : Check User Login SSH & SlowDNS"
echo -e "* member       : Daftar Member SSH & SlowDNS"
echo -e "* delete       : Delete User Expired SSH & SlowDNS"
echo -e "* autokill     : Set up Autokill SSH"
echo -e "* ceklim       : Displays Users Who Do Multi Login SSH"
echo -e "* restart      : Restart Service SSH & SlowDNS"
echo -e ""
echo -e "=============================-SYSTEM-=========================="
echo -e "* reboot       : Reboot VPS"
echo -e "* exit         : Exit From VPS "
echo -e ""
echo -e "==============================================================="
echo -e ""
